const API='https://gtizcgurtirpwmzsexyl.supabase.co/functions/v1/game-api';
const Q=[['light','Ты когда-нибудь делал вид, что не заметил сообщение, чтобы не отвечать?'],['light','Ты когда-нибудь отменял встречу, потому что хотелось остаться дома?'],['light','Ты когда-нибудь гуглил самого себя?'],['open','Ты когда-нибудь читал чужую переписку без разрешения?'],['open','Ты когда-нибудь завидовал близкому другу?'],['open','Ты когда-нибудь проверял телефон партнёра?'],['adult','Ты когда-нибудь отправлял очень откровенное фото?'],['adult','Ты когда-нибудь фантазировал о человеке, который сейчас в этой комнате?'],['adult','Ты когда-нибудь жалел утром о том, что произошло ночью?'],['wild','Ты когда-нибудь специально провоцировал ревность?'],['wild','Ты когда-нибудь использовал чужой секрет в своих интересах?'],['wild','Ты когда-нибудь поддерживал отношения только потому, что боялся остаться один?']];
let S={screen:'home',mode:'solo',level:'mix',rounds:15,name:'',room:null,player:null,players:[],host:false,picked:[],guess:null,sent:false};
const save=()=>localStorage.setItem('chesno-session',JSON.stringify({room:S.room,player:S.player,host:S.host,picked:S.picked}));
async function api(action,data={}){let r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});let j=await r.json();if(!r.ok)throw Error(j.error||'Ошибка сервера');return j}
function questions(){let a=S.level==='mix'?Q:Q.filter(x=>x[0]===S.level);a=[...a].sort(()=>Math.random()-.5);while(a.length<S.rounds)a=a.concat([...a]);return a.slice(0,S.rounds).map(x=>x[1])}
function render(){let h='';if(S.screen==='home')h=`<div class=wrap><div class=brand>party game</div><h1 class=hero>Честно?</h1><p class=muted>Анонимные ответы. Ставки на друзей. И открытия, которые лучше оставить в этой комнате.</p><div class=card><button class="btn hot" onclick="S.screen='setup';render()">Создать игру</button><button class="btn ghost" onclick="joinScreen()">Войти по коду</button></div><p class=tiny>3–30 игроков · телефоны · без регистрации</p></div>`;
if(S.screen==='setup')h=`<div class=wrap><div class=brand>Новая игра</div><h2>Как играем?</h2><div class=card><input id=name class=field maxlength=24 placeholder="Твоё имя"><label>Режим</label><select id=mode class=field><option value=solo>👤 Каждый за себя</option><option value=teams>🔴🔵 Команда против команды</option><option value=couples>❤️ Пара против пары</option></select><label>Вопросы</label><select id=level class=field><option value=mix>🎲 Всё вперемешку</option><option value=light>🙂 Лайт</option><option value=open>🌶 Откровенно</option><option value=adult>🔥 18+</option><option value=wild>☠️ Жесть</option></select><label>Длина игры</label><select id=rounds class=field><option>15</option><option>30</option><option>50</option></select><button class="btn hot" onclick="createRoom()">Создать комнату</button></div></div>`;
if(S.screen==='join')h=`<div class=wrap><div class=brand>Вход</div><h2>Присоединиться</h2><div class=card><input id=code class=field maxlength=5 placeholder="Код комнаты" value="${new URLSearchParams(location.search).get('room')||''}"><input id=name class=field maxlength=24 placeholder="Твоё имя"><button class="btn hot" onclick="joinRoom()">Войти</button></div></div>`;
if(S.screen==='lobby')h=lobby();if(S.screen==='game')h=game();document.getElementById('app').innerHTML=h}
function lobby(){let link=`${location.origin}${location.pathname}?room=${S.room.code}`;return `<div class=wrap><div class=brand>Комната</div><div class="card center"><div class=tiny>КОД ИГРЫ</div><div class=code>${S.room.code}</div><div id=qr></div><p class=muted>${link}</p></div><div class=card><b>Игроки (${S.players.length})</b><p>${S.players.map(x=>`<span class=pill>${x.name}</span>`).join('')}</p>${S.host?'<button class="btn hot" onclick="startGame()">Начать игру</button>':'<p class=muted>Ждём, когда ведущий начнёт игру…</p>'}</div></div>`}
function game(){let r=S.room,n=S.players.length;if(r.stage==='vote')return `<div class=wrap><div class=brand>Раунд ${r.current_round} из ${r.total_rounds}</div><div class=card><div class=tiny>ОТВЕТЬ ЧЕСТНО. НИКТО НЕ УВИДИТ.</div><div class=question>${r.question_text}</div>${S.sent?'<p class=muted>Ответ принят. Ждём остальных…</p>':'<div class=row><button class="btn yes" onclick="vote(true)">ДА</button><button class="btn no" onclick="vote(false)">НЕТ</button></div>'}${S.host?'<button class="btn ghost" onclick="advance()">Все ответили →</button>':''}</div></div>`;if(r.stage==='bet')return `<div class=wrap><div class=brand>Ставка</div><div class=card><div class=question>Сколько из ${n} человек ответили «ДА»?</div>${S.sent?'<p class=muted>Ставка принята. Ждём остальных…</p>':`<div class=grid>${Array.from({length:n+1},(_,i)=>`<button class=num onclick="predict(${i})">${i}</button>`).join('')}</div>`}${S.host?'<button class="btn ghost" onclick="advance()">Показать результат →</button>':''}</div></div>`;if(r.stage==='reveal')return `<div class=wrap><div class="card center"><div class=emoji>😈</div><div class=big>${r.yes_count} из ${n}</div><p>ответили «ДА»</p></div><div class=card><button class="btn ghost" onclick="confess()">😈 Я признаюсь</button>${S.host?`<button class="btn hot" onclick="advance()">${r.current_round>=r.total_rounds?'Итоги':'Следующий вопрос'}</button>`:''}</div></div>`;if(r.stage==='finished')return `<div class=wrap><div class="card center"><div class=emoji>🏆</div><h2>Игра окончена</h2></div><div class=card>${[...S.players].sort((a,b)=>b.score-a.score).map((x,i)=>`<div class=score><span>${i+1}. ${x.name}</span><b>${x.score}</b></div>`).join('')}</div></div>`;return `<div class=wrap><div class=card>Считаем результаты…</div></div>`}
async function createRoom(){try{S.name=document.querySelector('#name').value.trim();if(!S.name)return alert('Введи имя');S.mode=document.querySelector('#mode').value;S.level=document.querySelector('#level').value;S.rounds=+document.querySelector('#rounds').value;S.picked=questions();let j=await api('create',{name:S.name,mode:S.mode,level:S.level,rounds:S.rounds});S.room=j.room;S.player=j.player;S.players=[j.player];S.host=true;S.screen='lobby';save();render();poll()}catch(e){alert(e.message)}}
function joinScreen(){S.screen='join';render()}async function joinRoom(){try{let code=document.querySelector('#code').value.trim(),name=document.querySelector('#name').value.trim();let j=await api('join',{code,name});S.room=j.room;S.player=j.player;S.host=false;S.screen='lobby';save();render();poll()}catch(e){alert(e.message)}}
async function startGame(){await api('advance',{player_token:S.player.player_token,host_token:S.room.host_token,question:S.picked[0]});S.sent=false}
async function vote(answer){await api('vote',{player_token:S.player.player_token,answer});S.sent=true;render()}
async function predict(guess){await api('predict',{player_token:S.player.player_token,guess});S.sent=true;render()}
async function confess(){await api('confess',{player_token:S.player.player_token});alert('Признание опубликовано 😈')}
async function advance(){try{let next=S.picked[S.room.current_round]||null;await api('advance',{player_token:S.player.player_token,host_token:S.room.host_token,question:next});S.sent=false}catch(e){alert(e.message)}}
async function poll(){if(!S.room)return;setInterval(async()=>{try{let u='https://gtizcgurtirpwmzsexyl.supabase.co/rest/v1/';let key='';/* realtime client key injected at deploy */if(!key)return;}catch{}},1500)}
if(new URLSearchParams(location.search).has('room'))S.screen='join';render();