import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json"};
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
const code=()=>Math.random().toString(36).slice(2,7).toUpperCase();
async function playerByToken(token:string){return (await db.from('players').select('*').eq('player_token',token).single()).data}
async function room(id:string){return (await db.from('rooms').select('*').eq('id',id).single()).data}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const b=await req.json();const a=b.action;
if(a==='create'){let c=code();const r=(await db.from('rooms').insert({code:c,mode:b.mode||'solo',level:b.level||'mix',total_rounds:b.rounds||15}).select().single()).data!;const p=(await db.from('players').insert({room_id:r.id,name:(b.name||'Ведущий').slice(0,24),team:0}).select().single()).data!;return out({room:r,player:p});}
if(a==='join'){const r=(await db.from('rooms').select('*').eq('code',String(b.code).toUpperCase()).single()).data;if(!r||r.stage!=='lobby')return out({error:'Комната не найдена или игра уже началась'},400);const count=(await db.from('players').select('*',{count:'exact',head:true}).eq('room_id',r.id)).count||0;if(count>=30)return out({error:'В комнате уже 30 игроков'},400);const p=(await db.from('players').insert({room_id:r.id,name:String(b.name||'Игрок').slice(0,24),team:r.mode==='solo'?null:count%2}).select().single()).data;return out({room:r,player:p});}
const p=await playerByToken(b.player_token);if(!p)return out({error:'Сессия игрока не найдена'},401);const r=await room(p.room_id);if(a==='vote'){if(r.stage!=='vote')return out({error:'Сейчас нельзя голосовать'},409);await db.from('answers').upsert({room_id:r.id,round_no:r.current_round,player_id:p.id,answer:!!b.answer});const n=(await db.from('answers').select('*',{count:'exact',head:true}).eq('room_id',r.id).eq('round_no',r.current_round)).count;return out({ok:true,submitted:n});}
if(a==='predict'){if(r.stage!=='bet')return out({error:'Сейчас нельзя делать ставку'},409);await db.from('predictions').upsert({room_id:r.id,round_no:r.current_round,player_id:p.id,guess:+b.guess});return out({ok:true});}
if(a==='confess'){if(r.stage!=='reveal')return out({error:'Признаться можно после результата'},409);const ans=(await db.from('answers').select('answer').eq('room_id',r.id).eq('round_no',r.current_round).eq('player_id',p.id).single()).data;if(ans)await db.from('confessions').upsert({room_id:r.id,round_no:r.current_round,player_id:p.id,answer:ans.answer});return out({ok:true});}
if(a==='advance'){if(String(b.host_token)!==String(r.host_token))return out({error:'Только ведущий управляет раундом'},403);const pc=(await db.from('players').select('*',{count:'exact',head:true}).eq('room_id',r.id)).count||0;if(r.stage==='lobby'){await db.from('rooms').update({stage:'vote',current_round:1,question_text:b.question}).eq('id',r.id);return out({ok:true});}if(r.stage==='vote'){const n=(await db.from('answers').select('*',{count:'exact',head:true}).eq('room_id',r.id).eq('round_no',r.current_round)).count||0;if(n<pc)return out({error:`Ответили ${n} из ${pc}`},409);await db.from('rooms').update({stage:'bet'}).eq('id',r.id);return out({ok:true});}if(r.stage==='bet'){const n=(await db.from('predictions').select('*',{count:'exact',head:true}).eq('room_id',r.id).eq('round_no',r.current_round)).count||0;if(n<pc)return out({error:`Сделали ставку ${n} из ${pc}`},409);const aa=(await db.from('answers').select('answer').eq('room_id',r.id).eq('round_no',r.current_round)).data||[];const yes=aa.filter(x=>x.answer).length;const pp=(await db.from('predictions').select('*').eq('room_id',r.id).eq('round_no',r.current_round)).data||[];for(const x of pp){const d=Math.abs(x.guess-yes),pts=d===0?3:d===1?2:d===2?1:0;await db.from('predictions').update({points:pts}).eq('room_id',r.id).eq('round_no',r.current_round).eq('player_id',x.player_id);const pl=(await db.from('players').select('score').eq('id',x.player_id).single()).data;await db.from('players').update({score:(pl?.score||0)+pts}).eq('id',x.player_id)}await db.from('rooms').update({stage:'reveal',yes_count:yes}).eq('id',r.id);return out({ok:true,yes_count:yes});}if(r.stage==='reveal'){if(r.current_round>=r.total_rounds){await db.from('rooms').update({stage:'finished'}).eq('id',r.id)}else await db.from('rooms').update({stage:'vote',current_round:r.current_round+1,question_text:b.question,yes_count:null}).eq('id',r.id);return out({ok:true});}}
return out({error:'Неизвестное действие'},400)}catch(e){return out({error:String(e?.message||e)},500)}});